[2025-03-03T16:36:50.924+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:36:09.097634+00:00 [queued]>
[2025-03-03T16:36:50.934+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:36:09.097634+00:00 [queued]>
[2025-03-03T16:36:50.934+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T16:36:50.950+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): data_preparation_task> on 2025-03-03 16:36:09.097634+00:00
[2025-03-03T16:36:50.955+0000] {standard_task_runner.py:57} INFO - Started process 3946 to run task
[2025-03-03T16:36:50.958+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'data_preparation_task', 'manual__2025-03-03T16:36:09.097634+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpw0ji0kjf']
[2025-03-03T16:36:50.961+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask data_preparation_task
[2025-03-03T16:36:50.983+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T16:36:51.027+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.data_preparation_task manual__2025-03-03T16:36:09.097634+00:00 [running]> on host 157237bff8f7
[2025-03-03T16:36:51.137+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='data_preparation_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T16:36:09.097634+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T16:36:09.097634+00:00'
[2025-03-03T16:36:51.138+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T16:36:51.138+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/*** &&\t\t\tpython /opt/***/executables/data_preparation.py &&                         dvc add /opt/***/data/cleaned &&                         git add /opt/***/data/cleaned.dvc && \t\t\tgit add logs && \\   \n\t\t\tgit add visualization &&    \t\t\tgit status &&                         git commit -m "Updated cleaned data version" -a &&                         dvc push && git push\n                    ']
[2025-03-03T16:36:51.148+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T16:36:54.036+0000] {subprocess.py:93} INFO - 2025-03-03 16:36:54,036 : INFO : Starting data preparation for customer_data.csv.
[2025-03-03T16:36:54.065+0000] {subprocess.py:93} INFO - 2025-03-03 16:36:54,065 : INFO : Dropping 'Tenure' less than 0 and greater than 110 * 12
[2025-03-03T16:36:54.066+0000] {subprocess.py:93} INFO - 2025-03-03 16:36:54,065 : ERROR : Error in preparing data'tenure'
[2025-03-03T16:36:54.066+0000] {subprocess.py:93} INFO - 2025-03-03 16:36:54,066 : INFO : Starting data preparation for database_data.csv.
[2025-03-03T16:36:54.066+0000] {subprocess.py:93} INFO - 2025-03-03 16:36:54,066 : ERROR : Error in preparing data[Errno 2] No such file or directory: '/opt/***/data/raw/fintech2/03-03-2025/database/database_data.csv'
[2025-03-03T16:36:56.906+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:56.907+0000] {subprocess.py:93} INFO - To track the changes with git, run:
[2025-03-03T16:36:56.907+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:56.907+0000] {subprocess.py:93} INFO - 	git add data/cleaned.dvc
[2025-03-03T16:36:56.907+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:56.907+0000] {subprocess.py:93} INFO - To enable auto staging, run:
[2025-03-03T16:36:56.909+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:56.909+0000] {subprocess.py:93} INFO - 	dvc config core.autostage true
[2025-03-03T16:36:57.239+0000] {subprocess.py:93} INFO - /bin/bash: line 2:  : command not found
[2025-03-03T16:36:57.265+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T16:36:57.265+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T16:36:57.266+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:57.266+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T16:36:57.266+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T16:36:57.266+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:36:09.097634+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T16:36:57.266+0000] {subprocess.py:93} INFO - 	new file:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:36:09.097634+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T16:36:57.267+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_processor_manager/dag_processor_manager.log
[2025-03-03T16:36:57.267+0000] {subprocess.py:93} INFO - 	modified:   logs/data_preparation.log
[2025-03-03T16:36:57.267+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:57.267+0000] {subprocess.py:93} INFO - Changes not staged for commit:
[2025-03-03T16:36:57.267+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to update what will be committed)
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO -   (use "git restore <file>..." to discard changes in working directory)
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO - 	modified:   logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:36:09.097634+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T16:36:57.268+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/online_store.db
[2025-03-03T16:36:57.269+0000] {subprocess.py:93} INFO - 	customer_churn_stats/feature_repo/data/registry.db
[2025-03-03T16:36:57.269+0000] {subprocess.py:93} INFO - 	models/
[2025-03-03T16:36:57.269+0000] {subprocess.py:93} INFO - 	online.db
[2025-03-03T16:36:57.269+0000] {subprocess.py:93} INFO - 
[2025-03-03T16:36:57.330+0000] {subprocess.py:93} INFO - [main 376acbc] Updated cleaned data version
[2025-03-03T16:36:57.330+0000] {subprocess.py:93} INFO -  4 files changed, 107 insertions(+)
[2025-03-03T16:36:57.331+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:36:09.097634+00:00/task_id=data_preparation_task/attempt=1.log
[2025-03-03T16:36:57.331+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T16:36:09.097634+00:00/task_id=data_validation_task/attempt=1.log
[2025-03-03T16:37:02.932+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-03-03T16:37:05.030+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T16:37:05.031+0000] {subprocess.py:93} INFO -    4d878f9..376acbc  main -> main
[2025-03-03T16:37:05.039+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T16:37:05.078+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=data_preparation_task, execution_date=20250303T163609, start_date=20250303T163650, end_date=20250303T163705
[2025-03-03T16:37:05.118+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T16:37:05.152+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
