[2025-03-03T12:49:54.606+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-03T12:48:27.320795+00:00 [queued]>
[2025-03-03T12:49:54.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-03T12:48:27.320795+00:00 [queued]>
[2025-03-03T12:49:54.617+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-03T12:49:54.632+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): feature_store_task> on 2025-03-03 12:48:27.320795+00:00
[2025-03-03T12:49:54.637+0000] {standard_task_runner.py:57} INFO - Started process 1575 to run task
[2025-03-03T12:49:54.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'feature_store_task', 'manual__2025-03-03T12:48:27.320795+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmp_mhhyo2g']
[2025-03-03T12:49:54.643+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask feature_store_task
[2025-03-03T12:49:54.665+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-03-03T12:49:54.709+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.feature_store_task manual__2025-03-03T12:48:27.320795+00:00 [running]> on host 157237bff8f7
[2025-03-03T12:49:54.830+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='feature_store_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T12:48:27.320795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-03T12:48:27.320795+00:00'
[2025-03-03T12:49:54.831+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-03T12:49:54.833+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n\t\t\tcd /opt/***/customer_churn_stats/feature_repo &&                         feast apply &&                         feast materialize-incremental $(date -u +\'%Y-%m-%dT%H:%M:%S\') &&       \t\t\tgit add /opt/***/logs\n   \t\t\tgit status &&                         git commit -m "Updated feature store" -a &&                         git push\n                    ']
[2025-03-03T12:49:54.844+0000] {subprocess.py:86} INFO - Output:
[2025-03-03T12:50:00.665+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:00,664 : INFO : Connecting to Database
[2025-03-03T12:50:00.691+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:00,690 : INFO : Connecting to Database Successfull
[2025-03-03T12:50:00.691+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:00,691 : INFO : Reading data from database.
[2025-03-03T12:50:01.204+0000] {subprocess.py:93} INFO - /opt/***/customer_churn_stats/feature_repo/feature_store.py:36: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-03-03T12:50:01.205+0000] {subprocess.py:93} INFO -   data = pd.read_sql(query, connection)
[2025-03-03T12:50:01.205+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:01,204 : INFO : Data collection from database successfull!!
[2025-03-03T12:50:01.205+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:01,204 : INFO : Declaring an entity for the dataset
[2025-03-03T12:50:01.205+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:01,204 : INFO : Declaring the source for raw feature data
[2025-03-03T12:50:01.206+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:01,205 : INFO : Defining the features in a feature view
[2025-03-03T12:50:01.208+0000] {subprocess.py:93} INFO - 2025-03-03 12:50:01,208 : INFO : Feature view creation successfull!!
[2025-03-03T12:50:01.241+0000] {subprocess.py:93} INFO - No changes to registry
[2025-03-03T12:50:01.241+0000] {subprocess.py:93} INFO - No changes to infrastructure
[2025-03-03T12:50:08.136+0000] {subprocess.py:93} INFO - Materializing [1m[32m1[0m feature views to [1m[32m2025-03-03 12:50:02+00:00[0m into the [1m[32msqlite[0m online store.
[2025-03-03T12:50:08.136+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:50:08.137+0000] {subprocess.py:93} INFO - [1m[32mcustomer_stats_fv[0m from [1m[32m2025-03-02 15:37:33+00:00[0m to [1m[32m2025-03-03 12:50:02+00:00[0m:
[2025-03-03T12:50:08.141+0000] {subprocess.py:93} INFO - 0it [00:00, ?it/s]0it [00:00, ?it/s]
[2025-03-03T12:50:08.864+0000] {subprocess.py:93} INFO - On branch main
[2025-03-03T12:50:08.864+0000] {subprocess.py:93} INFO - Your branch is up to date with 'origin/main'.
[2025-03-03T12:50:08.864+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:50:08.864+0000] {subprocess.py:93} INFO - Changes to be committed:
[2025-03-03T12:50:08.865+0000] {subprocess.py:93} INFO -   (use "git restore --staged <file>..." to unstage)
[2025-03-03T12:50:08.865+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:48:27.320795+00:00/task_id=data_storage_task/attempt=1.log
[2025-03-03T12:50:08.865+0000] {subprocess.py:93} INFO - 	new file:   ../../logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:48:27.320795+00:00/task_id=feature_store_task/attempt=1.log
[2025-03-03T12:50:08.865+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/dag_processor_manager/dag_processor_manager.log
[2025-03-03T12:50:08.865+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/feature_store.log
[2025-03-03T12:50:08.866+0000] {subprocess.py:93} INFO - 	modified:   ../../logs/scheduler/2025-03-03/customer_churn.py.log
[2025-03-03T12:50:08.866+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:50:08.866+0000] {subprocess.py:93} INFO - Untracked files:
[2025-03-03T12:50:08.866+0000] {subprocess.py:93} INFO -   (use "git add <file>..." to include in what will be committed)
[2025-03-03T12:50:08.866+0000] {subprocess.py:93} INFO - 	data/online_store.db
[2025-03-03T12:50:08.867+0000] {subprocess.py:93} INFO - 	data/registry.db
[2025-03-03T12:50:08.867+0000] {subprocess.py:93} INFO - 	../../models/
[2025-03-03T12:50:08.867+0000] {subprocess.py:93} INFO - 	../../online.db
[2025-03-03T12:50:08.867+0000] {subprocess.py:93} INFO - 
[2025-03-03T12:50:08.902+0000] {subprocess.py:93} INFO - [main cdddb0b] Updated feature store
[2025-03-03T12:50:08.902+0000] {subprocess.py:93} INFO -  5 files changed, 80 insertions(+)
[2025-03-03T12:50:08.902+0000] {subprocess.py:93} INFO -  create mode 100644 logs/dag_id=customer_churn_ml_pipeline/run_id=manual__2025-03-03T12:48:27.320795+00:00/task_id=feature_store_task/attempt=1.log
[2025-03-03T12:50:10.589+0000] {subprocess.py:93} INFO - To https://github.com/anniemathew-trial/customer_churn_pipeline.git
[2025-03-03T12:50:10.589+0000] {subprocess.py:93} INFO -    6f931a6..cdddb0b  main -> main
[2025-03-03T12:50:10.594+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-03T12:50:10.629+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=feature_store_task, execution_date=20250303T124827, start_date=20250303T124954, end_date=20250303T125010
[2025-03-03T12:50:10.671+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-03T12:50:10.700+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
