[2025-02-28T04:35:18.764+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.dvc_pull manual__2025-02-28T04:35:17.945041+00:00 [queued]>
[2025-02-28T04:35:18.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customer_churn_ml_pipeline.dvc_pull manual__2025-02-28T04:35:17.945041+00:00 [queued]>
[2025-02-28T04:35:18.783+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-28T04:35:18.814+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): dvc_pull> on 2025-02-28 04:35:17.945041+00:00
[2025-02-28T04:35:18.820+0000] {standard_task_runner.py:57} INFO - Started process 7320 to run task
[2025-02-28T04:35:18.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'customer_churn_ml_pipeline', 'dvc_pull', 'manual__2025-02-28T04:35:17.945041+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/customer_churn.py', '--cfg-path', '/tmp/tmpqejx28vw']
[2025-02-28T04:35:18.830+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask dvc_pull
[2025-02-28T04:35:18.877+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-28T04:35:18.978+0000] {task_command.py:416} INFO - Running <TaskInstance: customer_churn_ml_pipeline.dvc_pull manual__2025-02-28T04:35:17.945041+00:00 [running]> on host 4470298645d8
[2025-02-28T04:35:19.199+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='customer_churn_ml_pipeline' AIRFLOW_CTX_TASK_ID='dvc_pull' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T04:35:17.945041+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T04:35:17.945041+00:00'
[2025-02-28T04:35:19.201+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-28T04:35:19.202+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/*** && dvc pull']
[2025-02-28T04:35:19.216+0000] {subprocess.py:86} INFO - Output:
[2025-02-28T04:35:22.548+0000] {subprocess.py:93} INFO - Everything is up to date.
[2025-02-28T04:35:23.010+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-28T04:35:23.081+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=customer_churn_ml_pipeline, task_id=dvc_pull, execution_date=20250228T043517, start_date=20250228T043518, end_date=20250228T043523
[2025-02-28T04:35:23.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-28T04:35:23.199+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
